set "CMAKE_FLAGS=-DCMAKE_INSTALL_PREFIX=%PREFIX%"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_BUILD_TYPE=Release"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_TESTING=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_EXAMPLES=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_OPENCL_TESTS=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_CUDA_TESTS=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_C_AND_FORTRAN_WRAPPERS=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_DRUDE_OPENCL_LIB=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_RPMD_OPENCL_LIB=OFF"

set "CMAKE_FLAGS=%CMAKE_FLAGS% -DOPENMM_BUILD_PME_PLUGIN=OFF"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DFFTW_LIBRARY=%LIBRARY_LIB%\libfftw3f-3.lib"
set "CMAKE_FLAGS=%CMAKE_FLAGS% -DFFTW_INCLUDES=%LIBRARY_INC%"

WHERE clcache
IF errorlevel 0 (
    set "CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_C_COMPILER=clcache"
    set "CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_CXX_COMPILER=clcache"
)

mkdir build
cd build
cmake -G "NMake Makefiles" %SRC_DIR% %CMAKE_FLAGS%
jom install
if errorlevel 1 exit 1

jom PythonInstall
if errorlevel 1 exit 1

%PYTHON% %RECIPE_DIR%\rewrite-version.py
if errorlevel 1 exit 1